name: build-check

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Generate Prisma Client
        run: npm run prisma:generate
        
      - name: Run Turborepo build
        run: npm run build

      - name: Verify build outputs
        run: |
          if [ ! -d "apps/merchant-app/.next" ]; then
            echo "Merchant App build failed: '.next' directory does not exist."
            exit 1
          fi
          if [ ! -d "apps/user-app/.next" ]; then
            echo "User App build failed: '.next' directory does not exist."
            exit 1
          fi
          if [ ! -d "apps/bank-webhook/dist" ]; then
            echo "Bank-webhook build failed: 'dist' directory does not exist."
            exit 1
          fi
          echo "All builds completed successfully!"
